# Generated by Django 4.2.5 on 2023-09-16 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_id_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6a835353-db80-478a-92ea-42ea0e605303"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
