# Generated by Django 4.2.5 on 2023-09-16 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_cover_alter_book_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"permissions": [("special_status", "Call read all books")]},
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("041110a2-3105-4112-92b1-e5e0a89046fc"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
